apiVersion: apps/v1
kind: Deployment
metadata:
  name: heic2avif-py-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heic2avif-py
  template:
    metadata:
      labels:
        app: heic2avif-py
    spec:
      containers:
      - name: heic2avif-py
        image: heic2avif-py:latest
        ports:
        - containerPort: 3001
        env:
        - name: PHOTOVAULT_API_URL
          value: "http://photovault-api:3001"
        - name: CALLBACK_TIMEOUT
          value: "30"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: heic2avif-py-service
  namespace: default
spec:
  selector:
    app: heic2avif-py
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
